"""Shared schemas for AIC 2026 Video Retrieval."""

from .contracts import (
    ASRSegment,
    Candidate,
    CandidateEvidence,
    FrameRecord,
    KISResult,
    ObjectDetection,
    ObjectRecord,
    OCRRecord,
    QACandidate,
    QAResult,
    QueryEvent,
    QueryRequest,
    SearchResponse,
    SubmissionRequest,
    SubmissionResponse,
    TRAKECandidate,
    TRAKEEventPrediction,
    TRAKEResult,
    TaskType,
    VideoRecord,
)

__all__ = [
    "ASRSegment",
    "Candidate",
    "CandidateEvidence",
    "FrameRecord",
    "KISResult",
    "ObjectDetection",
    "ObjectRecord",
    "OCRRecord",
    "QACandidate",
    "QAResult",
    "QueryEvent",
    "QueryRequest",
    "SearchResponse",
    "SubmissionRequest",
    "SubmissionResponse",
    "TRAKECandidate",
    "TRAKEEventPrediction",
    "TRAKEResult",
    "TaskType",
    "VideoRecord",
]
